### PR TITLE
Replace travis CI with Github actions

### PR DESCRIPTION
**Pull request by warmwaffles**
This also incorporates an update to VCR and a pinning of test config variables.

Ideally, we wouldn't use vcr and instead use [mox](https://hexdocs.pm/mox/Mox.html).

### CODE REVIEW

**Comment by warmwaffles** [comment]
Let me know about your thoughts on replacing VCR with mox. I would also like to add more tests later.

**Comment by warmwaffles** [comment]
Example of the action run results https://github.com/warmwaffles/auth0_ex/actions/runs/1970867257

**Comment by techgaun** [comment]
@warmwaffles thanks for this. Yeah I agree that Mox would be a great addition instead of vcr. Feel free to do so if you have time.

**Review by techgaun — APPROVED** [review]
:ok_hand: :purple_heart: :fire: :100: :rocket: **LGTM** :rocket: :100: :fire: :purple_heart: :ok_hand:

appreciate the help here.

**Comment by warmwaffles** [comment]
I'll hop on more tests here soon.

**Pull request merged**
