### PR TITLE
Allow signup with extra params

### PR DESCRIPTION
**Pull request by paridin**
This PR updates the dependencies of HTTPoison, to get an updated version of  hackney this is because [the error](https://elixirforum.com/t/erlang-v-23-0-and-httpoison-error/31615/8)
```{:error,
 %{
   reason: {:options,
    {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}}
 }}
```

The main purpose is to extend the `Auth0Ex.Authentication.signup/4` to allow extra params to the payload.

It adds the `Auth0Ex.Authentication.signup/5` to pass extra params, they are merged to the payload, those params should be found at https://auth0.com/docs/api/authentication#signup

### CODE REVIEW

**Review by techgaun — APPROVED** [review]
:ok_hand: :purple_heart: :fire: :100: :rocket: **LGTM** :rocket: :100: :fire: :purple_heart: :ok_hand:

**Comment by paridin** [comment]
Thanks for accepting my PR; I hope you are having a good day; I have a question, is there a date to be released on `hex.pm`?

**Comment by techgaun** [comment]
thanks @paridin for reminder. https://hexdocs.pm/auth0_ex/0.7.0 is out

**Comment by paridin** [comment]
Thank you!!! ❤️ 💚 💙

**Pull request merged**
